## Vector Analysis

<ul>
<li>Review of vector representation</li>
<li>Vector Norm</li>
<li>Orthogonality</li>
<li>Eigenvector & Eigen values</li>
<li>Diagonalization</li>
</ul>

## Review of vector representation

<ul>
<li>vector</li>
<li>array</li>
<li>matrix</li>
</ul>

scalar - number(any number)
group of scalar is a VECTOR - [1,2,3,4]

collection of vector  - MATRIX

In [2]:
import numpy as np

In [3]:
scalar = np.array(5)
vector = np.array([1,2,3,4])
matrix = np.array([
                    [1,2,3,4,5,],
                    [6,7,8,9,10],
                    [11,12,13,14,15]
                    ])

## Cosine similarity
In a euclidean plane

cos() = (AB/|A|*|B|)



## VECTOR NORM
Euclidean distance = L2 Norm 

Manhattan distance = L1 Norm

dot product aralin

### Linear Transformation

Shifting something in the matrix



## Eucliden distance



cos() = (AB/|A|*|B|)

In [4]:
## EUCLIDEAN / L2 NORM

q = np.array([[0,1]])
p = np.array([[1,0.5]])

num = p @ np.transpose(q)
normq = np.linalg.norm(q)
normp = np.linalg.norm(p)
denom = normq * normp
theta = np.arccos(num/denom)
theta

array([[1.10714872]])

In [5]:
def cos_similarity(A,B):
    num = A @ np.transpose(B)
    norma = np.linalg.norm(A)
    normb = np.linalg.norm(B)
    sim = num/ (norma*normb)
    theta = np.arccos(sim)
    return theta,sim


## EIGENTHINGS

<ul>
<li>Linear dependence</li>
</ul>

In [59]:
## DIAGONALIZATION AND EIGENVECTOR

x = np.array([[0,1],[1,0]])
# print(x)

evals = np.linalg.eig(x)
evects = np.linalg.eig(x)


evectsT = np.transpose(evects[1])
evectsT_inv = np.linalg.inv(evectsT)


# d = evectsT @ x @ evectsT_inv
d = evectsT_inv @ x @ evectsT

print(d)

## decrypting

xd = evectsT @ d @ evectsT_inv

print(xd)

[[-1.  0.]
 [ 0.  1.]]
[[0. 1.]
 [1. 0.]]
